spec/fortnox/api/models/attributes/country_code_spec.rb
spec/fortnox/api/models/attributes/currency_spec.rb
spec/fortnox/api/models/attributes/dummy_model_context.rb
spec/fortnox/api/models/attributes/test_classes_context.rb

Removed code duplication from attributes specs

Test classes context added for attribute specs

---

lib/fortnox/api/models.rb
lib/fortnox/api/repositories.rb
lib/fortnox/api/validators.rb

Quick fix for including invoice classes. Maybe we introduce some automatic inclusion in the future, but for now on, I just need to be able to use these classes.

Invoice classes required

---

README.md

- Adds new status as of November 2016.
- Includes notes about multiple Access Tokens.
- Validations are removed
- Mappers and Types are added

Updates the readme to new codebase

---

README.md

Adds info about what Exceptions the gem can throw. Feel free to comment and improve this @d-Pixie :)

Adds Exception info to README

---

bin/console

Allows you to get a Pry session with everything you need to test the gem with
`$ bin/console`

Command for quick CLI testing during development

---

lib/fortnox/api/types/model.rb

Just a small style improvement (IMO)

Use detect for more idiomatic "find first item"

---

fortnox-api.gemspec
lib/fortnox/api/mappers.rb
lib/fortnox/api/mappers/base.rb
spec/fortnox/api/mappers/base_spec.rb

Avoid using Fixnum as type on all Rubys

---

lib/fortnox/api/circular_queue.rb
lib/fortnox/api/mappers/base/from_json.rb
lib/fortnox/api/repositories/base.rb
lib/fortnox/api/repositories/base/loaders.rb
lib/fortnox/api/types/document_row.rb
lib/fortnox/api/types/email_information.rb
lib/fortnox/api/types/invoice_row.rb
lib/fortnox/api/types/model.rb
lib/fortnox/api/types/order_row.rb
lib/fortnox/api/types/sized.rb
spec/fortnox/api/repositories/base_spec.rb

I hope you like the name of the PR :)

Rubocop update refactoring 2

---

spec/fortnox/api/circular_queue_spec.rb

Replaces #134 
Adds simple tests to CircularQueue

Adds spec for CircularQueue

---

.rubocop.yml
.travis.yml
CHANGELOG.md
README.md
fortnox-api.gemspec
lib/fortnox/api/mappers/base/from_json.rb
lib/fortnox/api/types.rb
spec/fortnox/api/circular_queue_spec.rb
spec/fortnox/api/repositories/invoice_spec.rb

All code changes are auto corrections by Rubocop.

Updates ruby version

---

lib/fortnox/api/types/document_row.rb
spec/fortnox/api/repositories/order_spec.rb
spec/fortnox/api/types/examples/document_row.rb
spec/support/matchers/type/attribute_matcher.rb
spec/vcr_cassettes/orders/save_with_nested_model.yml

Fixes 201 negative price on rows

---

lib/fortnox/api/types/document_row.rb
spec/fortnox/api/repositories/invoice_spec.rb
spec/fortnox/api/types/examples/document_row.rb
spec/vcr_cassettes/invoices/row_description_limit.yml

Fixes #206 increases row description limit

---

lib/fortnox/api/types/enums.rb

Fixes #215 adds new delivery type

---

lib/fortnox/api/models/customer.rb
lib/fortnox/api/types.rb
spec/fortnox/api/repositories/customer_spec.rb
spec/fortnox/api/types/sales_account_spec.rb
spec/vcr_cassettes/customers/fetch_with_sales_account.yml
spec/vcr_cassettes/customers/find_with_sales_account.yml
spec/vcr_cassettes/customers/save_new_with_sales_account.yml

Fixes #214. See the issue for more information. The Fortnox API is just stupid here...

Fix 214 sales account

---

.rubocop.yml
bin/get_tokens
fortnox-api.gemspec
lib/fortnox/api.rb
lib/fortnox/api/mappers/base/from_json.rb
lib/fortnox/api/mappers/base/to_json.rb
lib/fortnox/api/models/base.rb
lib/fortnox/api/types.rb
lib/fortnox/api/types/model.rb
lib/fortnox/api/types/nullable.rb
lib/fortnox/api/types/order_row.rb
lib/fortnox/api/types/required.rb
lib/fortnox/api/types/sized.rb
spec/fortnox/api/mappers/default_delivery_types_spec.rb
spec/fortnox/api/mappers/examples/mapper.rb
spec/fortnox/api/types/model_spec.rb
spec/support/matchers/type/enum_matcher.rb
spec/support/matchers/type/have_account_number_matcher.rb
spec/support/matchers/type/have_email_matcher.rb
spec/support/matchers/type/have_nullable_date_matcher.rb
spec/support/matchers/type/have_nullable_string_matcher.rb

This excludes rubocop thingies. 
@ehannes pls check, hopefully makes it easier to review.

fix: Bumps dependencies and fixes dry-thingies compatibility

---

CONTRIBUTE.md
DEVELOPER_README.md
README.md

It was time to update the readme :)
Here's how the new configuration table in the readme looks like:

Readme update

---

.rubocop.yml
bin/get_tokens
fortnox-api.gemspec
lib/fortnox/api/mappers/base/from_json.rb
lib/fortnox/api/mappers/base/to_json.rb
lib/fortnox/api/types/model.rb
spec/fortnox/api/mappers/base/from_json_spec.rb
spec/fortnox/api/mappers/base_spec.rb
spec/fortnox/api/repositories/article_spec.rb
spec/fortnox/api/repositories/base_spec.rb
spec/fortnox/api/repositories/customer_spec.rb
spec/fortnox/api/repositories/examples/find.rb
spec/fortnox/api/repositories/examples/only.rb
spec/fortnox/api/repositories/examples/search.rb
spec/fortnox/api/repositories/invoice_spec.rb
spec/fortnox/api/repositories/order_spec.rb
spec/fortnox/api/repositories/project_spec.rb
spec/fortnox/api/repositories/terms_of_payment_spec.rb
spec/fortnox/api/repositories/unit_spec.rb
spec/fortnox/api/types/country_spec.rb
spec/fortnox/api/types/email_spec.rb
spec/fortnox/api/types/housework_types_spec.rb
spec/fortnox/api/types/model_spec.rb
spec/support/helpers/when_performing_helper.rb
spec/support/matchers/type/attribute_matcher.rb
spec/support/matchers/type/have_nullable_date_matcher.rb
spec/support/matchers/type/have_nullable_matcher.rb
spec/support/matchers/type/have_nullable_string_matcher.rb
spec/support/matchers/type/require_attribute_matcher.rb
spec/support/matchers/type/type_matcher.rb

More Rubocop fixes. Adds **a lot** of new Rubocop cops.

Dry libs upgrade rubocop fixes new cops

---

lib/fortnox/api/models/base.rb
lib/fortnox/api/repositories/base.rb
lib/fortnox/api/repositories/base/savers.rb
spec/fortnox/api/mappers/base/from_json_spec.rb
spec/fortnox/api/mappers/base/to_json_spec.rb
spec/fortnox/api/mappers/contexts/json_conversion.rb
spec/fortnox/api/models/base_spec.rb
spec/fortnox/api/repositories/base_spec.rb
spec/support/helpers/configuration_helper.rb

Fix 238 update saved model with nil value

---

CHANGELOG.md
lib/fortnox/api/types/model.rb
spec/fortnox/api/types/model_spec.rb

Fix 242/allow string keys

---

lib/fortnox/api/models/article.rb
spec/fortnox/api/repositories/article_spec.rb
spec/fortnox/api/repositories/invoice_spec.rb
spec/vcr_cassettes/articles/limits/quantity_in_stock_min_value.yml
spec/vcr_cassettes/articles/limits/quantity_in_stock_rounding_positive_value.yml
spec/vcr_cassettes/invoices/row_delivered_quantity_decimals.yml
spec/vcr_cassettes/invoices/row_delivered_quantity_decimals_round_up.yml
spec/vcr_cassettes/invoices/row_price_limit.yml
spec/vcr_cassettes/invoices/row_price_limit_round_up.yml

* Fix limit on Article attribute `quantity_in_stock` as reported in #145
* Add tests for some rounding limits on Invoice Row (for verifying how the API works, nothing directly related to our code but since Fortnox has no documentation for these kind of things you kind of have to explore the API yourself 😄)

Update limits and specs

---

CHANGELOG.md
README.md
lib/fortnox/api/models/article.rb
lib/fortnox/api/types/model.rb
lib/fortnox/api/version.rb
spec/fortnox/api/repositories/article_spec.rb
spec/fortnox/api/repositories/invoice_spec.rb
spec/fortnox/api/types/model_spec.rb
spec/vcr_cassettes/articles/limits/quantity_in_stock_min_value.yml
spec/vcr_cassettes/articles/limits/quantity_in_stock_rounding_positive_value.yml
spec/vcr_cassettes/invoices/row_delivered_quantity_decimals.yml
spec/vcr_cassettes/invoices/row_delivered_quantity_decimals_round_up.yml
spec/vcr_cassettes/invoices/row_price_limit.yml
spec/vcr_cassettes/invoices/row_price_limit_round_up.yml

Updates readme with find with hash and removes info about collections that's not implemented as well as some fixes.

New version
